title: Git Workshop
description: Using git to build software
theme: just-the-docs

url: https://briggstwitchell.github.io/git-workshop/Introduction

aux_links:
  Workshop Repository: https://github.com/briggstwitchell/git-workshop

color_scheme: dark

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: red
  pro-tip:
    title: Pro-Tip
    color: blue
  terminal:
    title: "Terminal Output:"
    color: green
  exercise:
    title: ""
    color: yellow

mermaid:
  version: "10.2.2"
