title: Git Workshop
description: Using git to build software
theme: jekyll-theme-minimal

url: https://briggstwitchell.github.io/vscode_workshop/Introduction

aux_links:
  Workshop Repository: https://github.com/briggstwitchell/vscode_workshop

color_scheme: dark

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: red
  pro-tip:
    title: Pro-Tip
    color: blue
  terminal:
    title: "Terminal Output:"
    color: green
  exercise:
    title: ""
    color: yellow

mermaid:
  version: "10.2.2"

header_pages:
  - sections/Basic-Commands.md
  - basic-commands/git-init.md